# Generated by Django 3.1.5 on 2021-01-29 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planilha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(blank=True, max_length=50)),
                ('documento', models.FileField(upload_to='criador_de_template/media/%Y/%m/%d/')),
                ('subido_as', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
