# Generated by Django 3.1.5 on 2021-02-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criador_de_template', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planilha',
            name='cliente',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='produto',
            name='cod_da_peca',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='produto',
            name='marca',
            field=models.CharField(max_length=100),
        ),
    ]
