# Generated by Django 3.1.5 on 2021-01-29 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criador_de_template', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planilha',
            name='documento',
            field=models.FileField(upload_to='media/%Y/%m/%d/'),
        ),
    ]
