# Generated by Django 3.1.5 on 2021-01-30 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criador_de_template', '0002_auto_20210129_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_da_peca', models.CharField(blank=True, max_length=10)),
                ('marca', models.CharField(blank=True, max_length=20)),
                ('descricao', models.CharField(blank=True, max_length=150)),
                ('aplicacao', models.CharField(blank=True, max_length=150)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
