# Generated by Django 3.1.5 on 2021-01-31 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criador_de_template', '0003_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='cliente',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='produto',
            name='destaque',
            field=models.BooleanField(default=False),
        ),
    ]
