# Generated by Django 3.1.5 on 2021-02-02 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('criador_de_template', '0004_auto_20210131_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='cliente',
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_name', models.CharField(blank=True, max_length=50)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='criador_de_template.produto')),
            ],
        ),
    ]
