# Generated by Django 3.1.5 on 2021-02-03 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('criador_de_template', '0005_auto_20210202_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='cliente',
        ),
        migrations.AddField(
            model_name='cliente',
            name='criado_em',
            field=models.DateField(auto_now=True, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='produtos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='criador_de_template.produto'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='aplicacao',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='cod_da_peca',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='destaque',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='marca',
            field=models.CharField(max_length=20),
        ),
    ]
