# Generated by Django 3.1.5 on 2021-02-03 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criador_de_template', '0006_auto_20210203_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='cliente',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
