# Generated by Django 3.1.5 on 2021-02-04 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('criador_de_template', '0008_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='cliente',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='criador_de_template.cliente'),
        ),
    ]
