# Generated by Django 3.1.5 on 2021-02-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criador_de_template', '0009_auto_20210204_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='criacao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
