# Generated by Django 3.1.5 on 2021-02-09 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('criador_de_template', '0011_auto_20210209_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='cliente',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='criador_de_template.cliente'),
        ),
    ]
