# Generated by Django 3.1.5 on 2021-02-10 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_profile_singup_confirmation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
